Repository vue-styled-components/core, pull requests merged in 2024-05, with the labels that each got.

#9 fix(core): animation doesn't working
  core/helper/keyframes.ts
  core/utils/injectStyle.ts
  docs/guide/basic/animations.md
Labels: bug

#11 feat(core): [styled] support passing type def for props
  core/helper/css.ts
  core/styled.ts
  core/utils/injectStyle.ts
  core/utils/insertExpressions.ts
  docs/.vitepress/en.ts
  docs/.vitepress/zh.ts
  docs/guide/advances/css-mixin.md
  docs/guide/advances/global-style.md
  docs/guide/api/hook.md
  docs/guide/basic/passing-props.md
  docs/package.json
  docs/zh/guide/advances/css-mixin.md
  docs/zh/guide/advances/global-style.md
  docs/zh/guide/api/hook.md
  docs/zh/guide/basic/passing-props.md
  example/App.vue
  pnpm-lock.yaml
  tsconfig.json
Labels: enhancement

#12 feat(helper): [cssClass] add function to generate common class
  core/helper/css.ts
  core/helper/cssClass.ts
  core/helper/index.ts
  docs/guide/advances/css-mixin.md
  docs/guide/api/helper.md
  docs/zh/guide/advances/css-mixin.md
  docs/zh/guide/api/helper.md
  example/App.vue
Labels: feature
